@startuml registration_and_listing
|Поставщик|
start
:Открыть форму регистрации;
:Заполнить данные;
|Платформа|
:Проверить корректность данных;
if (Данные корректны?) then (Да)
  :Отправить на модерацию;
  |Администратор|
  :Проверка продавца;
  if (Продавец одобрен?) then (Да)
    |Платформа|
    :Создать личный кабинет;
    |Поставщик|
    :Войти в личный кабинет;
    :Создать карточку товара;
    :Добавить описание, цену, фото;
    :Сохранить черновик;
    |Платформа|
    :Проверка карточки (модерация);
    if (Карточка одобрена?) then (Да)
      :Опубликовать товар;
    else (Нет)
      :Отклонить с комментарием;
    endif
  else (Нет)
    |Платформа|
    :Отклонить регистрацию;
  endif
else (Нет)
  :Показать ошибку ввода;
endif
stop
@enduml
